pipeline {
  agent any

  stages {

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t 3tier-app ./app'
      }
    }

    stage('Terraform Init') {
      steps {
        sh 'cd terraform && terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh 'cd terraform && terraform plan'
      }
    }

    stage('Terraform Apply') {
      steps {
        sh 'cd terraform && terraform apply -auto-approve'
      }
    }

  }
}